version: '3'
services:
  app:
    build: .
    volumes:
      # Mount the X11 socket
      - /dev/bus/usb:/dev/bus/usb # Forwards the local USB devices to the container.
      - /dev/input:/dev/input # Forwards the local input devices to the container.
    
